user_name=input("Введите имя пользователя")
print("Имя пользователя:", user_name)
title=input("Введите заголовок заметки")
print("заголовок заметки:", title)
content=input("Введите описание заметки")
print("описание заметки:", content)
status=input("Введите статус заметки")
print("статус заметки:", status)
created_date=input("Введите дату создания заметки в формате 'день-месяц-год")
print(created_date[0:5])
issue_date=input('Введите дату истечения заметки (дедлайн) в формате "день-месяц-год"')
print( issue_date[0:5])
