user_name=input("Введите имя пользователя")
print("Имя пользователя:", user_name)
title1=input("Введите заголовок заметки:")
title2=input("Персонажи")
title3=input("Рекомендации для чтения")
title4=input("Основные темы")
print("заголовок заметки:",[title1,title2,title3,title4])
content=input("Введите описание заметки")
print("описание заметки:", content)
status=input("Введите статус заметки")
print("статус заметки:", status)
created_date=input("Введите дату создания заметки в формате 'день-месяц-год")
print(created_date[0:5])
issue_date=input('Введите дату истечения заметки (дедлайн) в формате "день-месяц-год"')
print( issue_date[0:5])
note=[user_name,content,created_date,issue_date,[title1,title2,title3,title4]]
print(note)